name: pepecoin-mainnet

services:
  core:
    image: pepeenthusiast/pepecoin-core:latest
    restart: unless-stopped
    command:
        -printtoconsole
        -server=1
        -txindex=1
        -rpcallowip=0.0.0.0/0
        -rpcuser=rpc
        -rpcpassword=rpcp
    volumes:
        - core_data:/home/pepecoin/.pepecoin
  electrs:
    image: pepeenthusiast/electrs:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    command: |
      --jsonrpc-import
      --address-search
      --index-unspendables
      --rest-default-chain-txs-per-page 10
      --daemon-rpc-addr core:33873
      --daemon-dir /.pepecoin
      --cookie rpc:rpcp
      --db-dir /electrs
      --cors '*'
    volumes:
    - core_data:/.pepecoin
    - electrs_data:/electrs
  holders:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ELECTRS_URL=http://electrs:3000
      - HTTP_PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - holders_data:/app/data/

volumes:
  core_data:
  electrs_data:
  holders_data: